---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

```

```{css}
body{ 
background-image: linear-gradient(to right,#ffffe0,#ffffff)
}

```

## Self-study Procrastination Survey

This survey analyzes my study procrastination patterns, covering task types, time management, emotional triggers, and intervention strategies.
```{r, echo=FALSE}
library(tidyverse)
logged_data <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vR2ky8wjsBENUDN0i0kzQsm9crN0ogqIAJO-8ejE2VHbvqmBfRVMhYIo5PLQ2AhTzK73ini5gjbm7zb/pub?gid=465914163&single=true&output=csv")
latest_data <- logged_data %>%
  rename(Time = 1,
         Type = 2,
         long = 3,
         expected_Diff = 4,
         actual_Diff = 5,
         Score = 6,
         Emotion = 7,
         Strategy = 8,
         Effect = 9)


#bar chart1
latest_data$long <- factor(latest_data$long,
                           levels = c("Less than 1 hour","1 - 3 hours","4 - 5 hours","More than 5 hours"))

long_bar <- ggplot(latest_data)+
  geom_bar(aes(x = long), fill = "#c1e8ff")+
  labs(title = "How long did you procrastinate?",
       x = "Procrastination duration")
long_bar

#dynamic comment 1
counts <- latest_data%>%
  count(long)
count1 <- counts%>% 
  filter(long == "Less than 1 hour") %>% pull(n)
count2 <- counts%>% 
  filter(long == "1 - 3 hours") %>% pull(n)
count3 <- counts%>% 
  filter(long == "4 - 5 hours") %>% pull(n)
count4 <- counts%>% 
  filter(long == "More than 5 hours") %>% pull(n)
paste0("The x-axis represents different procrastination duration categories. ")
paste0("The category 'Less than 1 hour' has a count of ", count1, ".")
paste0("The '1 - 3 hours' category has ", count2, " occurrences.")
paste0(" The '4 - 5 hours' category has a count of ", count3, ".")
paste0("The 'More than 5 hours' category has a count of ", count4, ".")



#bar chart2:
score_bar <- ggplot(latest_data)+
  geom_bar(aes(x = Score), fill = "#7da0ca")+
  labs(title = "How strongly did you resist starting? ",
       x = "Resistance level")
score_bar

#dynamic comment 2
mean_score <- mean(latest_data$Score)
num_t <- length(latest_data$long)



```

